//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noisrev.Rion {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Noisrev.Rion.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 e768df4620 10year_startup_tip_1000
        ///6768df4620 10Year_Startup_Tip_1000
        ///7d846fa111 10year_startup_tip_1001
        ///e7943a2c9b 10year_startup_tip_1002
        ///67943a2c9b 10Year_Startup_Tip_1002
        ///cfacee91c8 10year_startup_tip_1003
        ///4facee91c8 10Year_Startup_Tip_1003
        ///cfbec5c16b 10year_startup_tip_1004
        ///4fbec5c16b 10Year_Startup_Tip_1004
        ///f1986fb3b5 10year_startup_tip_1005
        ///71986fb3b5 10Year_Startup_Tip_1005
        ///2555eda6c5 10year_startup_tip_1006
        ///2c584b68fe 10year_startup_tip_1007
        ///1127b1308f 10year_startup_tip_1008
        ///11fdf47091 10year_star [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RSTHashes {
            get {
                return ResourceManager.GetString("RSTHashes", resourceCulture);
            }
        }
    }
}
